### ISSUE TITLE
JDFixer 3.0.0 seems to rely on codegen 0.28.0

### ISSUE THREAD

**Issue by YoLeax** [Metalit/QuestJDFixer#4]
The mod importer (not BMBF) I am using says JDFixer 3.0.0 relies on codegen 0.28.0, instead of the latest 0.32.0. This makes me unable to install JDFixer. I'm not sure it's the mod importer's problem or JDFixer's.

**Comment by ghost** [comment]
You mean QuestAppVersionSwitcher ans the other Mod Manager arent you?

**Comment by YoLeax** [comment]
> You mean QuestAppVersionSwitcher ans the other Mod Manager arent you?

Nope~ I'm using a modified QuestPatcher:
https://github.com/MicroCBer/QuestPatcher

**Comment by Metalit** [comment]
It's an issue with the released qmod. I'll release a fixed version shortly
