### ISSUE TITLE
Scores will not save or upload with JDFixer enabled.

### ISSUE THREAD

**Issue by Wil-dTrick** [Metalit/QuestJDFixer#6]
Did an entire round of process of elimination. Disabled all other non-core mods. It's not related to Noodle. Song ends, score shows. Score does not save even locally any time JDFixer is installed.

**Comment by Wil-dTrick** [comment]
Wanted to add, speeds are not tweaked when testing.  They're just set to default.

**Comment by Metalit** [comment]
If you have the toggle on to override the NJS it's going to disable score submission even if the speed is the same as the level

**Comment by Wil-dTrick** [comment]
Does that also prevent it from saving locally? That's what was really throwing me off. I will try that though as soon as my quest charges. This very well could be whatever the VR version of PEBKAC is.

**Comment by Metalit** [comment]
Yes, it prevents the score from saving anywhere, the same as if you had played in practice mode - it's also similar to how practice doesn't count even at normal speed

**Comment by Wil-dTrick** [comment]
That's definitely going to fix the problem then. I'll let the others who use it know as well.
